- name: Purge snapd
  apt:
    name: snapd
    state: absent
    purge: yes
    autoremove: yes
  become: yes

- name: Install NodeSource signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes

- name: Add NodeSource deb repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main
  become: yes

- name: Add NodeSource deb-src repository
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main
  become: yes

- name: Install packages
  apt:
    name:
      - pcscd
      - pcsc-tools
      - libpcsclite-dev
      - dvb-tools
      - nodejs
      - git
      - build-essential
    update_cache: yes
    cache_valid_time: 3600
  become: yes
