- name: Clone dvbconf repository
  git:
    repo: https://github.com/Chinachu/dvbconf-for-isdb.git
    dest: /usr/local/dvbconf
  become: yes

- name: Install PM2
  npm:
    name: pm2
    global: yes
  become: yes

- name: Install Mirakurun
  npm:
    name: mirakurun
    global: yes
    unsafe_perm: yes
    production: yes
  become: yes

- name: Install arib test
  npm:
    name: arib-b25-stream-test
    global: yes
    unsafe_perm: yes
  become: yes

- name: Copy tuner config
  copy:
    src: ./files/tuners.yml
    dest: /usr/local/etc/mirakurun/tuners.yml
    owner: root
    group: root
  become: yes
  register: copy_tuner_config

- name: Restart mirakurn
  command: mirakurun restart
  become: yes
  when: copy_tuner_config.changed

- name: Scan channels
  uri:
    url: http://localhost:40772/api/config/channels/scan
    method: PUT
    timeout: 3600
    status_code: 200
    return_content: yes
  when: copy_tuner_config.changed
  changed_when: true
  register: scan_channels
  until: scan_channels.status == 200
  retries: 5
  delay: 5

- name: Restart mirakurn
  command: mirakurun restart
  become: yes
  when: copy_tuner_config.changed
