---
- name: Install NodeSource signing key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: true

- name: Add NodeSource deb repository
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  become: true
  loop:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"

- name: Install packages
  apt:
    name:
      - pcscd
      - pcsc-tools
      - libpcsclite-dev
      - dvb-tools
      - nodejs
      - git
      - build-essential
    update_cache: true
    cache_valid_time: 3600
  become: true
