---
- name: Copy udev rules
  copy:
    src: 91-tuner.rules
    dest: /etc/udev/rules.d/91-tuner.rules
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - reset_us_3pout
    - restart_mirakurn

- name: Install build-essential
  apt:
    name: build-essential
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Clone recfsusb2n
  git:
    repo: https://github.com/epgdatacapbon/recfsusb2n.git
    dest: "/home/{{ ansible_user }}/recfsusb2n"
    version: 46c64f7
  register: git_clone

- name: Make recfsusb2n
  community.general.make:
    chdir: "/home/{{ ansible_user }}/recfsusb2n/src"
    target: "{{ item }}"
  become: true
  when: git_clone.changed
  loop:
    - clean
    - all
    - install
  tags:
    - skip_ansible_lint

- name: Set recfsusb2n.conf
  copy:
    src: recfsusb2n.conf
    dest: /usr/local/bin/recfsusb2n.conf
    owner: root
    group: root
    mode: 0755
  become: true
