- name: Install PM2
  npm:
    name: pm2
    global: yes
  become: yes

- name: Install Mirakurun
  npm:
    name: mirakurun
    global: yes
    unsafe_perm: yes
    production: yes
  become: yes
  notify: restart_mirakurn

- name: Install arib test
  npm:
    name: arib-b25-stream-test
    global: yes
    unsafe_perm: yes
  become: yes
  notify: restart_mirakurn

- name: Clone dvbconf repository
  git:
    repo: https://github.com/Chinachu/dvbconf-for-isdb.git
    dest: /usr/local/dvbconf
  become: yes
  notify: restart_mirakurn

- name: Copy tuner config
  template:
    src: tuners.yml.j2
    dest: /usr/local/etc/mirakurun/tuners.yml
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart_mirakurn
