- name: Clone dvbconf repository
  git:
    repo: https://github.com/Chinachu/dvbconf-for-isdb.git
    dest: /usr/local/dvbconf
  become: yes
  notify: Rescan channels

- name: Install PM2
  npm:
    name: pm2
    global: yes
  become: yes

- name: Install Mirakurun
  npm:
    name: mirakurun
    global: yes
    unsafe_perm: yes
    production: yes
  become: yes
  notify: Rescan channels

- name: Install arib test
  npm:
    name: arib-b25-stream-test
    global: yes
    unsafe_perm: yes
  become: yes
  notify: Rescan channels

- name: Copy tuner config
  copy:
    src: ./files/tuners.yml
    dest: /usr/local/etc/mirakurun/tuners.yml
    owner: root
    group: root
  become: yes
  register: copy_tuner_config
  notify: Rescan channels
