---
- name: Restart zabbix
  systemd:
    name: "{{ item }}"
    state: reloaded
  listen: restart_zabbix
  become: true
  loop:
    - zabbix-server.service
    - zabbix-agent.service
    - apache2.service
