---
- name: Reload nftables
  systemd:
    name: nftables.service
    state: reloaded
    enabled: true
  listen: reload_nftables
  become: true

- name: Restart netfilter-persistent
  systemd:
    name: netfilter-persistent.service
    state: restarted
    enabled: true
  listen: restart_netfilter_persistent
  become: true
