- name: Install nftables
  apt:
    name:
      - nftables
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Enable nftables
  systemd:
    name: nftables.service
    state: started
    enabled: yes
  become: yes

- name: Set ntftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0744
    validate: nft -c -f %s
  become: yes
  notify: Reload nftables
