- name: Set authorized key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: yes

- name: Set hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost {{ inventory_hostname }}"
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Set timezone
  timezone:
    name: Asia/Tokyo
  become: yes
