---
- name: Set authorized key
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  become: true

- name: Set hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost {{ inventory_hostname }}"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Set timezone
  timezone:
    name: Asia/Tokyo
  become: true

- name: Install avahi-daemon
  apt:
    name:
      - avahi-daemon
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Enable avahi-daemon
  systemd:
    name: avahi-daemon.service
    state: started
    enabled: true
  become: true
