---
- name: Install iptables-persistent
  apt:
    name:
      - iptables-persistent
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  notify: reload_netfilter_persistent

- name: Set rules.v4
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0644
    validate: iptables-restore --test %s
  become: yes
  notify: restart_netfilter_persistent

- name: Set rules.v6
  template:
    src: rules.v6.j2
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: 0644
    validate: ip6tables-restore --test %s
  become: yes
  notify: restart_netfilter_persistent
